# Generated by Django 5.1.1 on 2024-10-23 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='rating',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='blog',
            old_name='is_bestselling',
            new_name='slug',
        ),
    ]
